"""empty message

Revision ID: 0b872d476761
Revises: d8bbd744ccf9
Create Date: 2026-09-20 10:50:45.348501

"""
from typing import Sequence, Union

from alembic import op
import pgvector
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b872d476761'
down_revision: Union[str, Sequence[str], None] = 'd8bbd744ccf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Tasks', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=100),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=16),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Tasks', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=16),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=100),
               existing_nullable=True)
    # ### end Alembic commands ###
