"""empty message

Revision ID: 53692827fa14
Revises: d31e6d0712f5
Create Date: 2026-09-20 11:54:54.408519

"""
from typing import Sequence, Union

from alembic import op
import pgvector
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53692827fa14'
down_revision: Union[str, Sequence[str], None] = 'd31e6d0712f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Tasks', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=100),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=1024),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Tasks', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=1024),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=100),
               existing_nullable=True)
    # ### end Alembic commands ###
