"""empty message

Revision ID: d8bbd744ccf9
Revises: e1b3c120dfcf
Create Date: 2026-09-19 20:45:59.281623

"""
from typing import Sequence, Union

from alembic import op
import pgvector
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8bbd744ccf9'
down_revision: Union[str, Sequence[str], None] = 'e1b3c120dfcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Tasks', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Tasks', 'embedding')
    # ### end Alembic commands ###
