name: Python packahe

on: [push]

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/checkout@v5
        with:
          python-version: "3.14"
          architecture: "x64"

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
